import Anthropic from "@anthropic-ai/sdk";
import { pool } from "../../db.js";

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export interface TextDetectionInput {
  documentId: string;
}

export interface TextDetectionFlag {
  excerpt: string;
  reason: string;
}

export interface TextDetectionOutput {
  score: number;
  risk: "LOW" | "MEDIUM" | "HIGH";
  summary: string;
  flags: TextDetectionFlag[];
}

export async function detectAiText(input: TextDetectionInput): Promise<TextDetectionOutput> {
  const { documentId } = input;

  const docResult = await pool.query(
    `SELECT final_text FROM documents WHERE id = $1`,
    [documentId]
  );

  const doc = docResult.rows[0];
  if (!doc) throw Object.assign(new Error("Document not found"), { status: 404 });

  const text = (doc.final_text ?? "").replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim();
  if (text.length < 100) {
    throw Object.assign(
      new Error("Document is too short for reliable AI detection."),
      { status: 400 }
    );
  }

  const message = await client.messages.create({
    model: "claude-haiku-4-5-20251001",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are an academic integrity tool analyzing whether a student essay was written by a human or generated by AI.

Analyze the following text for signs of AI generation. Look for: unnaturally consistent sentence length, generic transitions ("Furthermore", "Moreover", "In conclusion"), lack of personal voice or specific details, perfect grammar with no natural errors, hedging phrases typical of AI ("It is important to note"), overly balanced structure, and absence of authentic perspective.

Text to analyze:
"""
${text}
"""

Return a JSON object with exactly these fields:
- "score": integer 0-100 representing probability the text is AI-generated (0 = definitely human, 100 = definitely AI)
- "risk": one of "LOW", "MEDIUM", or "HIGH" (LOW = 0-30, MEDIUM = 31-65, HIGH = 66-100)
- "summary": one sentence explaining the overall assessment
- "flags": array of up to 5 objects, each with:
  - "excerpt": exact short quote from the text (10-20 words) that looks AI-generated
  - "reason": one sentence explaining why this excerpt is suspicious

Return ONLY valid JSON, no text outside the object.`,
      },
    ],
  });

  const raw = message.content[0].type === "text" ? message.content[0].text : "";

  let result: TextDetectionOutput | null = null;
  try {
    const match = raw.match(/\{[\s\S]*\}/);
    result = match ? JSON.parse(match[0]) : null;
  } catch {
    result = null;
  }

  if (!result) throw new Error("Failed to parse detection result");

  return result;
}
